#!/bin/sh

# PROVIDE: celery
# REQUIRE: LOGIN
# KEYWORD: shutdown nojail

. /etc/rc.subr

name="celery"
rcvar=`set_rcvar`
start_cmd="${name}_start"
stop_cmd="${name}_stop"

# commande à exécuter pour démarrer le daemon celery
celery_start()
{
    echo "Starting celery"
    /home/celery/info-f-309/webview/ve/bin/python \
    -m celery worker -A webview \
    --pidfile=/var/run/celery/celeryd.pid \
    --logfile=/var/log/celery/celeryd.log \
    --workdir=/home/celery/info-f-309/webview/ \
    --uid=celery --gid=celery -l INFO --detach
}

# commande pour connaître l'état de celery
celery_status()
{
    /home/celery/info-f-309/webview/ve/bin/python \
    -m celery info -A webview \
    --pidfile=/var/run/celery/celeryd.pid \
    --logfile=/var/log/celery/celeryd.log \
    --workdir=/home/celery/info-f-309/webview/ \
    --uid=celery --gid=celery
}

# commande pour stopper celery
celery_stop()
{
    kill $(cat /var/run/celery/celeryd.pid)
}

load_rc_config $name
run_rc_command "$1"
