# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('E', 'Erreur'), ('D', 'Done'), ('W', 'Waiting')], db_index=True, default='PREPARING', max_length=20, verbose_name='État')),
                ('zipFile', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('pdf', models.FileField(blank=True, null=True, upload_to='pdf/')),
            ],
        ),
    ]
