# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clean',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('E', 'Erreur'), ('D', 'Done'), ('W', 'Waiting')], db_index=True, default='W', max_length=20, verbose_name='État'),
        ),
    ]
