# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20160417_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='zipFile',
            field=models.FileField(upload_to='uploads/', validators=[documents.models.validate_file_extension]),
        ),
    ]
